[profile.default]
src = "src"
out = "out"
libs = ["lib"]

ffi = true
fs_permissions = [{ access = "read-write", path = "./" }]

solc = "0.8.23"
optimize=true
optimize_runs=20000
evm_version="paris"

[profile.gas]
test = 'test/gas'
match-test = 'test_Gas_**'

#  FOUNDRY_PROFILE=gas forge snapshot -vvv

#viaIR = true this some how breaks the invariant test

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

## https://explorer.testnet.rsk.co/
RSK_RPC_URL="https://public-node.testnet.rsk.co"

## chain id 43113
## https://testnet.snowtrace.io/

