[profile.default]
src = "src"
out = "out"
libs = ["lib"]

ffi = true
fs_permissions = [{ access = "read-write", path = "./" }]

solc = "0.8.19"
optimize=true
optimize_runs=20000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

## https://explorer.testnet.rsk.co/
RSK_RPC_URL="https://public-node.testnet.rsk.co"

## chain id 43113
## https://testnet.snowtrace.io/
FUJI_RPC_URL="https://endpoints.omniatech.io/v1/avax/fuji/public"

#fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}]

[profile.optimizor]
#viaIR = true
